# -*- coding: utf-8 -*-
"""model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trChFSMxtsM45JomVYJtKXvzTJuhxJRR
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

df = pd.read_csv("/content/feature_engineered_dataset.csv")

# List of categorical columns to encode
categorical_cols = ['category', 'region', 'weather_condition', 'seasonality']

# Apply one-hot encoding to the DataFrame
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# 'units_sold' taken as target because pricing decisions depend on demand prediction.
# Predicting price directly is harder.
y = df["units_sold"]

# all the columns except target and identifier columns.
x = df.drop(["units_sold", "date", "store_id", "product_id"], axis=1)

# splits dataset into training and testing data in 80 :20
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=42 )

# creates an XGBoost regression model with hyperparameters
# n_estimators - - model will build 100 decision trees sequentially. Each tree tries to correct the errors of the previous one
# learning_rate -  Controls how much each tree contributes to the final prediction
# max_depth - Limits the depth of each decision tree

xgb_model = xgb.XGBRegressor( n_estimators=100, learning_rate=0.1, max_depth=6 )

# trains the xgboost model on training data
xgb_model.fit(x_train, y_train)

# predicts on testing data
y_pred_xgb = xgb_model.predict(x_test)

# calcuates rmse for xgb model
# the average difference between the predicted values and the actual values
# Lower RMSE → better accuracy (predictions are closer to actual outcomes)
# Higher RMSE → worse accuracy (predictions deviate more from reality)

rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
print("XGBoost RMSE:", rmse_xgb)

# Since the target variable is units_sold, RMSE ≈ 0.894 means that,
# on average, the model’s predictions differ from the actual sales by less than 1 unit.
# This is quite a good result, showing that the model is predicting sales with high accuracy.

# creates light gb model
lgb_model = lgb.LGBMRegressor( n_estimators=100, learning_rate=0.1, max_depth=6 )

# Train the LightGBM Regressor model using the training data
lgb_model.fit(x_train, y_train)

y_pred_lgb = lgb_model.predict(x_test)

# Calculate the Root Mean Squared Error (RMSE) for the LightGBM model's predictions

rmse_lgb = np.sqrt(mean_squared_error(y_test, y_pred_lgb))
print("LightGBM RMSE:", rmse_lgb)

# Output explanation:
# The output 'LightGBM RMSE: 1.0054242124118193' indicates that, on average, the LightGBM model's predictions
# for 'units_sold' deviate from the actual values by approximately 1.01 units. A lower RMSE value
# generally indicates a better-performing model, as it means the predictions are closer to the true values.
# Comparing this to the XGBoost RMSE (0.89), the XGBoost model performed slightly better on this dataset
# in terms of prediction accuracy.

fig, ax= plt.subplots(figsize=(10, 8))
xgb.plot_importance(xgb_model,ax=ax)
plt.show()

"""### Explanation of XGBoost Feature Importance Plot

The plot above visualizes the feature importance as determined by the XGBoost model. Here's what it tells us:

*   **Y-axis**: Lists the features (columns) from your dataset that were used in training the `xgb_model`.
*   **X-axis**: Represents the 'F-score', which is the number of times a feature is split on across all boosting trees. A higher F-score indicates that the feature is used more frequently in the model's decision-making process, suggesting it is more important for predicting the target variable (`units_sold`).

**Interpretation:**

By looking at the bars, you can identify which features contributed most significantly to the model's performance. Features with longer bars (higher F-scores) are considered more important by the XGBoost model.

"""

# for each row in dataset, we now have the model's predicted demand based on the input features
df["predicted_demand"] = xgb_model.predict(x)

# the predicted demand is higher than what was actually sold, it suggests that the product might have been underpriced.
#the function recommends increasing the current price by 5%. This is an attempt to capitalize on the higher demand. and vice versa.

def optimize_price(row):
  if row["predicted_demand"] > row["units_sold"]:
    return row["price"] * 1.05
  else:
    return row["price"] * 0.95

df["ml_price"] = df.apply(optimize_price, axis=1)

#line applies the optimize_price function to each row (axis=1) of DataFrame df
# and stores the resulting optimized price in a new column called ml_price.

# calculates the projected revenue if the optimized pricing strategy was applied.

df["ml_revenue"] = df["ml_price"] * df["units_sold"]

# calculates the revenue generated by the actual sales at the actual prices.

df["baseline_revenue"] = df["price"] * df["units_sold"]

# calculates total revenue lift

lift = (df["ml_revenue"].sum() - df["baseline_revenue"].sum()) / df["baseline_revenue"].sum() * 100
print("ML Revenue Lift (%):", lift)

#A positive value indicates that your machine learning-driven pricing strategy would have generated more total revenue than your baseline pricing, representing a percentage increase.
#A negative value indicates that the ML-driven pricing strategy would have resulted in less total revenue, representing a percentage decrease.

# observations
"""
- Target & Features:
- Target variable: units_sold.
- Features: All other relevant columns (excluding units_sold, date, store_id, product_id).

- Model Performance:
- XGBoost RMSE ≈ 0.894 → better accuracy.
- LightGBM RMSE ≈ 1.005 → slightly worse.
- Observation: XGBoost outperformed LightGBM in predicting sales.

- Feature Importance (XGBoost):
- Certain features (like demand_ratio, conversion_rate) had stronger influence on predictions.

- ML Pricing Strategy:
- Rule: Increase price by 5% if predicted demand > actual sales, else decrease by 5%.
- Revenue Lift = -0.0345% → very small negative impact.
- Observation: The simple 5% adjustment logic did not improve revenue.

- Overall Conclusion:
- XGBoost is a reliable predictor of demand.
- However, the pricing optimization strategy needs refinement — demand elasticity and
  more sophisticated optimization should be considered instead of fixed percentage changes.
"""