# -*- coding: utf-8 -*-
"""optimized_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17J_gqy47RFFwJYK2xmW_EeY6Vs9DTP1L
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

df = pd.read_csv("/content/feature_engineered_dataset.csv")

# List of categorical columns to encode
categorical_cols = ['category', 'region', 'weather_condition', 'seasonality']

# Apply one-hot encoding to the DataFrame
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# it creates a train set with all data points before '2022-10-01' and a test set with all data points from '2022-10-01' onwards.
# This ensures that the model is trained on past data and evaluated on future data, mimicking a real-world scenario.
# time-based split
df = df.sort_values("date")
train =df[df["date"] < "2022-10-01"]
test = df[df["date"] >= "2022-10-01"]

X_train = train.drop(["units_sold", "date","product_id","store_id"], axis=1)
y_train = train["units_sold"]
X_test =test.drop(["units_sold", "date","product_id","store_id"], axis=1)
y_test = test["units_sold"]

#creates xgb regressor model and trains it
model = xgb.XGBRegressor( n_estimators=300, learning_rate=0.05, max_depth=8, subsample=0.8, colsample_bytree=0.8 )
model.fit(X_train, y_train)

# finds the best hyperparameters for your XGBoost model
from sklearn.model_selection import RandomizedSearchCV
params = { "max_depth": [4,6,8], "learning_rate":
[0.01, 0.05, 0.1], "reg_alpha": [0, 0.001, 0.01, 0.1, 1],
"reg_lambda": [0, 0.001, 0.01, 0.1, 1] }
search = RandomizedSearchCV(model, params, n_iter=5)
search.fit(X_train, y_train)

import matplotlib.pyplot as plt
fig, ax= plt.subplots(figsize=(10, 8))
xgb.plot_importance(model,ax=ax)
plt.show()

features = [c for c in df.columns if c not in ["units_sold","date","product_id","store_id"]]

def find_best_price(row):
    prices = [row["price"] * i for i in [0.8, 0.9, 1.0, 1.1, 1.2]]
    # These are the current price multiplied by 80%, 90%, 100%, 110%, and 120%.
    # This allows the model to explore slight variations around the current price.
    best_price = row["price"]
    best_revenue = 0

    for p in prices:
        row_features = row.copy()
        row_features["price"] = p
        demand = model.predict(row_features[features].values.reshape(1, -1))[0]
        revenue = demand * p
        if revenue > best_revenue:
            best_revenue = revenue
            best_price = p
    return best_price

df["optimal_price"] = df.apply(find_best_price, axis=1)

# revenue of each product
revenues = []
for i in range(len(test)):
  row = test.iloc[i]
  price = find_best_price(row)
  revenue = price* row["units_sold"]
  revenues.append(revenue)

#calculates baseline revenue and ml revenue
#finding lift%
baseline = test["price"] * test["units_sold"]
ml = sum(revenues)
lift = (ml - baseline.sum()) /baseline.sum() * 100
print("Lift:", lift)

train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

train_rmse = np.sqrt(mean_squared_error(y_train, train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, test_pred))

print(f"Train RMSE: {train_rmse:.2f}")
print(f"Test RMSE: {test_rmse:.2f}")

"""If the `Train RMSE` is significantly lower than the `Test RMSE`, it indicates potential overfitting. Otherwise, the model is generalizing well."""

import shap
explainer = shap.Explainer(model)
shap_values = explainer(X_test)
shap.plots.beeswarm(shap_values)

