# -*- coding: utf-8 -*-
"""Baseline Pricing Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_iYnCQcXf4rFBIVSHl_qehb6BKjq4wK8
"""

import pandas as pd

# Load your feature engineered dataset
df = pd.read_csv('/content/feature_engineered_dataset.csv')

df.head()

def pricing_rule(row):

    price = row['price']

    # Rule 1: High demand → increase price
    if row['demand_forecast'] > 100:
        price = price * 1.10

    # Rule 2: High inventory → decrease price
    if row['inventory_level'] > 200:
        price = price * 0.90

    # Rule 3: Competitor cheaper → reduce price slightly
    if row['competitor_pricing'] < row['price']:
        price = price * 0.95

    return price

df['new_price'] = df.apply(pricing_rule, axis=1)

# Old revenue
df['old_revenue'] = df['price'] * df['units_sold']

# New revenue
df['new_revenue'] = df['new_price'] * df['units_sold']

df[['price', 'new_price', 'old_revenue', 'new_revenue']].head()

old_total = df['old_revenue'].sum()
new_total = df['new_revenue'].sum()

print("Old Revenue:", old_total)
print("New Revenue:", new_total)
print("Revenue Change:", new_total - old_total)

import matplotlib.pyplot as plt

labels = ['Old Revenue', 'New Revenue']
values = [old_total, new_total]

plt.bar(labels, values)
plt.title("Revenue Comparison")
plt.ylabel("Revenue")
plt.show()

df['price_change_%'] = ((df['new_price'] - df['price']) / df['price']) * 100