# -*- coding: utf-8 -*-
"""Exploratory Data Analysis (EDA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atiJGPoH6pl4-3TQy0-D-CKrB4qAibMp
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/feature_engineered_dataset.csv")
df.head()

df.shape
df.info()
df.describe()

"""Dataset has ___ rows and ___ columns
Contains numerical + categorical data

"Distribution of Numerical Features"
"""

import matplotlib.pyplot as plt

df.hist(figsize=(20,15), bins=30)

plt.suptitle("Distribution of Numerical Features", fontsize=16)

plt.tight_layout()
plt.show()

"""Relationship Analysis

Price vs Units Sold
"""

sns.scatterplot(x="price", y="units_sold", data=df)
plt.show()
plt.figure(figsize=(8,5))
sns.set(style="whitegrid")

"""If price increases, units sold decreases → demand is elastic

Inventory vs Sales
"""

sns.scatterplot(x="inventory_level", y="units_sold", data=df)
plt.show()
plt.figure(figsize=(8,5))
sns.set(style="whitegrid")

"""Visitors vs Sales"""

sns.scatterplot(x="visitors", y="units_sold", data=df)
plt.show()
plt.figure(figsize=(8,5))
sns.set(style="whitegrid")

"""Competitor Pricing"""

sns.scatterplot(x="competitor_pricing", y="price", data=df)
plt.show()
plt.figure(figsize=(8,5))
sns.set(style="whitegrid")

"""Correlation Heatmap"""

plt.figure(figsize=(14,10))

corr = df.select_dtypes(include='number').corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")

plt.xticks(rotation=45)
plt.yticks(rotation=0)

plt.title("Correlation Heatmap")
plt.show()

"""only important things"""

plt.figure(figsize=(10,6))

important_cols = [
    "price", "units_sold", "discount", "visitors",
    "revenue", "profit_margin", "inventory_level"
]

corr = df[important_cols].corr()

sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Correlation Heatmap (Important Features)")
plt.show()

""""Category vs Units Sold"
"""

sns.barplot(x="category", y="units_sold", data=df)
plt.xticks(rotation=45)
plt.show()

""""Region vs Units Sold"
"""

sns.barplot(x="region", y="units_sold", data=df)
plt.show()

""""Seasonality vs Units Sold"
"""

sns.boxplot(x="seasonality", y="units_sold", data=df)
plt.show()

""""Weather Condition vs Units Sold"
"""

sns.boxplot(x="weather_condition", y="units_sold", data=df)
plt.show()

""""Holiday/Promotion vs Units Sold"
"""

sns.barplot(x="holiday/promotion", y="units_sold", data=df)
plt.show()

""""Discount vs Units Sold"
"""

plt.figure(figsize=(8,5))

sns.boxplot(x="discount", y="units_sold", data=df)

plt.title("Discount vs Units Sold")
plt.xlabel("Discount")
plt.ylabel("Units Sold")

plt.show()

""""Revenue Distribution""Profit Margin Distribution"

> Add blockquote


"""

sns.histplot(df["revenue"], kde=True)
plt.show()

sns.histplot(df["profit_margin"], kde=True)
plt.show()

""""Sales Trend (7-Day Moving Average)"
"""

plt.figure(figsize=(10,5))

df["date"] = pd.to_datetime(df["date"])

daily_sales = df.groupby("date")["units_sold"].sum()

# Smooth the line
daily_sales.rolling(window=7).mean().plot()

plt.title("Sales Trend (7-Day Moving Average)")
plt.xlabel("Date")
plt.ylabel("Units Sold")

plt.show()

plt.figure(figsize=(10,5))

df["date"] = pd.to_datetime(df["date"])

df.groupby("month")["units_sold"].mean().plot(kind="bar")

plt.title("Average Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Units Sold")

plt.show()

""""Average Monthly Sales"
"""

df.groupby("month")["units_sold"].mean().plot(kind="bar")
plt.show()

""""Day of Week vs Units Sold"
"""

sns.barplot(x="day_of_week", y="units_sold", data=df)
plt.show()

""""Conversion Rate Distribution"
"""

# Create conversion rate column
df["conversion_rate"] = df["units_sold"] / df["visitors"].replace(0, 1)

import seaborn as sns
import matplotlib.pyplot as plt

df["conversion_rate"] = df["units_sold"] / df["visitors"].replace(0, 1)

plt.figure(figsize=(8,5))
sns.histplot(df["conversion_rate"], kde=True, bins=30)
plt.xlabel("Conversion Rate")
plt.ylabel("Frequency")
plt.title("Conversion Rate Distribution")
plt.show()

"""Conversion rate shows that only a portion of visitors convert into buyers, indicating opportunities to improve customer conversion strategies.

Additional graphs:


Inventory Pressure
Competitor Gap
Demand Ratio
"""

plt.figure(figsize=(8,5))

sns.histplot(df["inventory_pressure"], kde=True)

plt.title("Inventory Pressure Distribution")
plt.xlabel("Inventory Pressure")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["competitor_gap"], kde=True)

plt.title("Competitor Gap Distribution")
plt.xlabel("Competitor Gap")
plt.ylabel("Frequency")

plt.show()

"""“Inventory pressure shows stock availability trends affecting sales.”
“Competitor gap indicates pricing competitiveness.”

Price negatively affects demand
Discounts increase sales
Holidays boost revenue
Certain categories dominate
Competitor pricing influences ours

The exploratory data analysis reveals that pricing, discounts, and visitor traffic significantly influence sales. External factors such as seasonality, weather, and promotions also impact demand. The analysis highlights demand elasticity, where higher prices reduce sales, while discounts increase customer purchases. These insights will be useful for building a dynamic pricing model to optimize revenue and profitability.
"""