# -*- coding: utf-8 -*-
"""Model Development

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DPOLA4upIFYGvQoWWuJZp986zKxhIai
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd
df = pd.read_csv('/content/feature_engineered_dataset.csv')
df.head()

df.shape
df.info()
df.describe()

"""df.hist(figsize=(18, 12))
plt.suptitle('Distribution of Numerical Features', y=1.02, fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.98])
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x="price", y="units_sold", data=df)
plt.title('Units Sold vs. Price')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x="inventory_level", y="units_sold", data=df)
plt.title('Units Sold vs. Inventory Level')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x="competitor_pricing", y="price", data=df)
plt.title('Product Price vs. Competitor Pricing')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.scatterplot(x="visitors", y="units_sold", data=df)
plt.title('Units Sold vs. Visitors')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 10))
numeric_df = df.select_dtypes(include=np.number)
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix of Numerical Features')
plt.tight_layout()
plt.show()
"""

def pricing_rule(row):
    price = row['price']

    if row['demand_forecast'] > 100:
        price *= 1.10

    if row['inventory_level'] > 200:
        price *= 0.90

    if row['competitor_pricing'] < row['price']:
        price *= 0.95

    return price

df["dynamic_price"] = df.apply(pricing_rule, axis=1)

df["baseline_revenue"] = df["dynamic_price"] * df["units_sold"]

df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()

y = df["units_sold"]
X = df.drop(["units_sold", "date", "store_id", "product_id"], axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

import xgboost as xgb
import pandas as pd

# Identify categorical columns
categorical_cols = X_train.select_dtypes(include='object').columns

# Apply one-hot encoding to training data
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)

# Apply one-hot encoding to test data
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# Align columns - this is crucial if some categories are present in train but not test, or vice-versa
# Reindex X_test_encoded to match X_train_encoded columns, filling new columns with 0
missing_cols_in_test = set(X_train_encoded.columns) - set(X_test_encoded.columns)
for c in missing_cols_in_test:
    X_test_encoded[c] = 0
# Reindex X_test_encoded to ensure the order of columns is the same as X_train_encoded
X_test_encoded = X_test_encoded[X_train_encoded.columns]

model = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42 # Added for reproducibility
)

model.fit(X_train_encoded, y_train)

y_pred = model.predict(X_test_encoded)

from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)

# Identify categorical columns from X for encoding
categorical_cols_in_X = X.select_dtypes(include='object').columns
X_full_encoded = pd.get_dummies(X, columns=categorical_cols_in_X, drop_first=True)

# Align X_full_encoded with the columns of X_train_encoded (which the model expects)
# Get the columns that the model was trained on
model_trained_columns = X_train_encoded.columns

# Add missing columns to X_full_encoded and fill with 0
missing_cols = set(model_trained_columns) - set(X_full_encoded.columns)
for col in missing_cols:
    X_full_encoded[col] = 0

# Remove extra columns from X_full_encoded that were not in the training set
extra_cols = set(X_full_encoded.columns) - set(model_trained_columns)
X_full_encoded = X_full_encoded.drop(columns=list(extra_cols))

# Ensure the order of columns matches the training data
X_full_encoded = X_full_encoded[model_trained_columns]

df["predicted_demand"] = model.predict(X_full_encoded)

def ml_price(row):
    if row["predicted_demand"] > row["units_sold"]:
        return row["price"] * 1.05
    else:
        return row["price"] * 0.95

df["ml_price"] = df.apply(ml_price, axis=1)

df["ml_revenue"] = df["ml_price"] * df["units_sold"]

lift = (df["ml_revenue"].sum() - df["baseline_revenue"].sum()) / df["baseline_revenue"].sum() * 100

print("ML Revenue Lift (%):", lift)

labels = ["Baseline Revenue", "ML Revenue"]
values = [df["baseline_revenue"].sum(), df["ml_revenue"].sum()]

plt.bar(labels, values)
plt.title("Revenue Comparison")
plt.show()

import pickle

pickle.dump(model, open("model.pkl", "wb"))

"""Conclusion:

EDA helped identify key factors like demand, inventory, and pricing trends.
A rule-based pricing system was implemented for baseline comparison.
An XGBoost model was trained to predict demand and improve pricing decisions.
The ML-based pricing showed better revenue performance compared to the baseline system.
"""