# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HckveToy0AikN5xcMb-hB2lsdWo9-LVN
"""

import pandas as pd

df = pd.read_csv("Updated_dynamic-pricing-dataset.csv")
print(df.shape)   # Shows (rows, columns) →  (73100, 17)
print(df.head())  # Shows first 5 rows

print(df.dtypes)

df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

print(df.isnull().sum())

df["Price"] = df["Price"].fillna(df["Price"].median())
df["Cost"] = df["Cost"].fillna(df["Cost"].median())
df["Demand Forecast"] = df["Demand Forecast"].fillna(df["Demand Forecast"].median())

df["Weather Condition"] = df["Weather Condition"].fillna(df["Weather Condition"].mode()[0])

print("Duplicates found:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("After removal:", df.shape)

df.columns = df.columns.str.lower().str.replace(" ", "_")

print(df[df["inventory_level"] < 0])   # SEE the non valid rows first

df = df[df["inventory_level"] >= 0]    # KEEP only valid rows

print(df[df["units_sold"] > df["inventory_level"]])

df = df[df["units_sold"] <= df["inventory_level"]]

print(df[df["price"] <= 0])
df = df[df["price"] > 0]

print(df[df["cost"] > df["price"]])
#  remove these rows
df = df[df["cost"] <= df["price"]]

# First: convert from percentage to decimal
df["discount"] = df["discount"] / 100

# Then: check for any out-of-range values
print(df[(df["discount"] < 0) | (df["discount"] > 1)])

# Clip any remaining outliers to valid range
df["discount"] = df["discount"].clip(0, 1)

print(df[df["visitors"] < 0])

df = df[df["visitors"] >= 0]

# Category column
df["category"] = df["category"].str.strip().str.title()
# .strip() removes leading/trailing spaces: "  Toys  " → "Toys"
# .title() capitalizes first letter of each word: "toys" → "Toys"

# Weather condition
df["weather_condition"] = df["weather_condition"].str.title()

Q1 = df["price"].quantile(0.25)   # 25th percentile (lower quarter)
Q3 = df["price"].quantile(0.75)   # 75th percentile (upper quarter)
IQR = Q3 - Q1                      # Interquartile Range = middle 50% spread

lower = Q1 - 1.5 * IQR   # Anything below this = outlier
upper = Q3 + 1.5 * IQR   # Anything above this = outlier

df = df[(df["price"] >= lower) & (df["price"] <= upper)]

df.to_csv("clean_dynamic_pricing_dataset.csv", index=False)
print("Clean dataset saved! Shape:", df.shape)

