# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfMcfvR5cyWZijjUlg9n9DAgw-V6Kn4f
"""

# Import necessary libraries for data manipulation and visualization

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/feature_engineered_dataset.csv")
df.head()

# Display the shape of the DataFrame (number of rows, number of columns)
df.shape

# Display a concise summary of the DataFrame, including data types and non-null values
df.info()

# Generate descriptive statistics of the numerical columns in the DataFrame
df.describe()

# Create histograms for all numerical columns in the DataFrame
df.hist(figsize=(30,20))
# Display the plots
plt.show()

# Create a scatter plot to visualize the relationship between 'price' and 'units_sold'
sns.scatterplot(x="price", y="units_sold", data=df)
plt.show()

# Create a scatter plot to visualize the relationship between 'inventory_level' and 'units_sold'
sns.scatterplot(x="inventory_level", y="units_sold", data=df)
plt.show()

# Create a scatter plot to visualize the relationship between 'competitor_pricing' and 'price'
sns.scatterplot(x="competitor_pricing", y="price", data=df)
plt.show()

# Create a scatter plot to visualize the relationship between 'visitors' and 'units_sold'
sns.scatterplot(x="visitors", y="units_sold", data=df)
plt.show()

# Set the figure size for better visualization of the heatmap
plt.figure(figsize=(40,20))
# Create a heatmap to visualize the correlation matrix of numerical columns
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap="coolwarm")
plt.show()

# Iterate through each specified categorical column and create a bar plot
for column in ['category', 'region', 'weather_condition', 'seasonality']:
    # Create a new figure for each plot to ensure separate display
    plt.figure(figsize=(10, 6))
    # Generate the bar plot showing the mean 'units_sold' for each category
    sns.barplot(x=column, y="units_sold", data=df)
    # Set the title of the plot, formatting the column name for readability
    plt.title(f'Units Sold by {column.replace("_", " ").title()}')
    # Set the x-axis label, formatting the column name
    plt.xlabel(column.replace("_", " ").title())
    # Set the y-axis label
    plt.ylabel('Units Sold')
    # Rotate x-axis labels for better readability, especially if they are long
    plt.xticks(rotation=45, ha='right')
    # Adjust plot layout to prevent labels from overlapping
    plt.tight_layout()
    plt.show()

# Create a scatter plot to visualize the relationship between 'discount' and 'units_sold'
sns.scatterplot(x="discount", y="units_sold", data=df)
plt.show()

# Create a histogram to visualize the distribution of 'revenue', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["revenue"], kde=True)
plt.show()

# Create a histogram to visualize the distribution of 'profit_margin', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["profit_margin"], kde=True)
plt.show()

# Convert the 'date' column to datetime objects for time-series analysis
df["date"] = pd.to_datetime(df["date"])
# Group data by 'date' and plot the sum of 'units_sold' over time
df.groupby("date")["units_sold"].sum().plot(figsize=(10,5))
# Display the plot
plt.show()

# Group data by 'month' and plot the mean of 'units_sold' for each month as a bar chart
df.groupby("month")["units_sold"].mean().plot(kind="bar")
plt.show()

# Create a bar plot to compare 'units_sold' during weekends versus weekdays
sns.barplot(x="is_weekend", y="units_sold", data=df)
plt.show()

# Create a histogram to visualize the distribution of 'conversion_rate', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["conversion_rate"], kde=True)
plt.show()

# Create a histogram to visualize the distribution of 'inventory_pressure', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["inventory_pressure"], kde=True)
plt.show()

# Create a histogram to visualize the distribution of 'competitor_gap', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["competitor_gap"], kde=True)
plt.show()

# Create a histogram to visualize the distribution of 'demand_ratio', with a Kernel Density Estimate (KDE) curve
sns.histplot(df["demand_ratio"], kde=True)
plt.show()

# observations

"""
Inventory Level : Almost uniform distribution → evenly spread across values.
Units Sold : Right-skewed → more low sales, fewer high sales.
Units Ordered : Nearly uniform distribution.
Demand Forecast : Slightly right-skewed → higher values are less frequent.
Price : Uniform distribution → prices evenly distributed.
Discount : Only specific values (0, 5, 10, 15, 20) → discrete.
Holiday/Promotion : Binary (0 or 1) → mostly non-holiday days.
Competitor Pricing : Uniform distribution → competitors price similarly across range.
Visitors : Bell-shaped (normal-like) → most values around middle.
Cost : Slightly normal distribution
Profit Margin : Right-skewed → most margins are low to moderate.
Margin Percent : Fairly uniform.
Demand Ratio : Mostly concentrated near 0 → low variation.
Inventory Pressure : Uniform → evenly spread.
Competitor Gap : Centered around 0 → prices close to competitors.
Revenue : Highly right-skewed → few very high values.
Conversion Rate : Normal distribution → balanced.
Price Demand Ratio : Highly skewed → mostly small values.
Stock Remaining : Right-skewed → most products have low leftover stock.
Traffic Intensity : Right-skewed → mostly low traffic.
Price vs Units Sold  : No clear relationship→ Price does NOT strongly affect sales.
Inventory Level vs Units Sold : Positive relationship→ More inventory → more sales possible.
Competitor Pricing vs Price : Strong positive linear relation→ Your price follows competitor pricing closely.
Visitors vs Units Sold : Strong positive relationship→ More visitors → more sales.
Weather Condition :  Sales are almost same across all weather types.
Seasonality : Sales are consistent across seasons (no big variation).
Sales mainly depend on : Visitors, Demand Forecast, Inventory Level
"""