# -*- coding: utf-8 -*-
"""pricing model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGy-oj6NaJtrRshTSyheKNVQwCSsKQso
"""

!pip install xgboost lightgbm

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import xgboost as xgb
import lightgbm as lgb

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("feature_engineered_dataset.csv")
df.head()

print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

y = df["units_sold"]

X = df.drop(["units_sold", "date", "store_id", "product_id"], axis=1)

# Check categorical columns
categorical_cols = X.select_dtypes(include=['object']).columns
print("Categorical Columns:", categorical_cols)

# Apply One-Hot Encoding
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

print("After Encoding Shape:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

xgb_model = xgb.XGBRegressor(
    n_estimators=200,      # increased for better learning
    learning_rate=0.05,    # smaller for stability
    max_depth=6,
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

print("XGBoost RMSE:", rmse_xgb)

lgb_model = lgb.LGBMRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

lgb_model.fit(X_train, y_train)

y_pred_lgb = lgb_model.predict(X_test)

rmse_lgb = np.sqrt(mean_squared_error(y_test, y_pred_lgb))

print("LightGBM RMSE:", rmse_lgb)

print("Model Comparison:")
print(f"XGBoost RMSE: {rmse_xgb}")
print(f"LightGBM RMSE: {rmse_lgb}")

best_model = xgb_model if rmse_xgb < rmse_lgb else lgb_model
print("Best Model Selected:", type(best_model).__name__)

xgb.plot_importance(xgb_model)
plt.title("Feature Importance (XGBoost)")
plt.show()

df["predicted_demand"] = best_model.predict(X)

def optimize_price(row):
    demand_ratio = row["predicted_demand"] / (row["units_sold"] + 1)

    if demand_ratio > 1.2:
        return row["price"] * 1.10  # strong increase
    elif demand_ratio > 1:
        return row["price"] * 1.05  # mild increase
    elif demand_ratio < 0.8:
        return row["price"] * 0.90  # strong decrease
    else:
        return row["price"] * 0.95  # mild decrease

df["ml_price"] = df.apply(optimize_price, axis=1)

df["ml_revenue"] = df["ml_price"] * df["units_sold"]

df["dynamic_price"] = df["price"]

df["baseline_revenue"] = df["dynamic_price"] * df["units_sold"]

lift = (
    (df["ml_revenue"].sum() - df["baseline_revenue"].sum())
    / df["baseline_revenue"].sum()
) * 100

print("ML Revenue Lift (%):", lift)

plt.figure()
plt.bar(["Baseline", "ML Model"],
        [df["baseline_revenue"].sum(), df["ml_revenue"].sum()])

plt.title("Revenue Comparison")
plt.ylabel("Total Revenue")
plt.show()

plt.figure()
plt.scatter(df["units_sold"], df["predicted_demand"])
plt.xlabel("Actual Demand")
plt.ylabel("Predicted Demand")
plt.title("Actual vs Predicted Demand")
plt.show()

print("Conclusion:")
print("Check if ML revenue is higher than baseline.")
print("Analyze feature importance and demand predictions.")