# -*- coding: utf-8 -*-
"""pricing rule

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q83fWLzjpHSsVjd9Do4sRxZkblgi8akj
"""

# Install required libraries
!pip install xgboost shap optuna

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
import shap

from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error

np.random.seed(42)

dates = pd.date_range(start="2022-01-01", periods=500)

df = pd.DataFrame({
    "date": dates,
    "price": np.random.uniform(10, 100, size=500),
    "inventory": np.random.randint(50, 500, size=500),
    "competitor_price": np.random.uniform(10, 100, size=500),
})

# Demand logic (realistic simulation)
df["units_sold"] = (
    200
    - 1.5 * df["price"]
    + 0.8 * df["inventory"] / 10
    - 1.2 * df["competitor_price"]
    + np.random.normal(0, 5, size=500)
)

df["dynamic_price"] = df["price"] * np.random.uniform(0.9, 1.1, size=500)

df.head()

df = df.sort_values("date")

train = df[df["date"] < "2022-10-01"]
test = df[df["date"] >= "2022-10-01"]

print(train.shape, test.shape)

X_train = train.drop(["units_sold", "date"], axis=1)
y_train = train["units_sold"]

X_test = test.drop(["units_sold", "date"], axis=1)
y_test = test["units_sold"]

feature_cols = X_train.columns
print(feature_cols)

model = xgb.XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(X_train, y_train)

params = {
    "max_depth": [4, 6, 8],
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 200, 300]
}

search = RandomizedSearchCV(model, params, n_iter=5, cv=3)
search.fit(X_train, y_train)

model = search.best_estimator_

print("Best Params:", search.best_params_)

train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

print("Train MAE:", mean_absolute_error(y_train, train_pred))
print("Test MAE:", mean_absolute_error(y_test, test_pred))

print("Train RMSE:", np.sqrt(mean_squared_error(y_train, train_pred)))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, test_pred)))

xgb.plot_importance(model)
plt.title("Feature Importance")
plt.show()

def find_best_price(row):
    prices = [row["price"] * i for i in [0.8, 0.9, 1.0, 1.1, 1.2]]

    best_price = row["price"]
    best_revenue = 0

    for p in prices:
        temp = row.copy()
        temp["price"] = p

        demand = model.predict([temp.drop("units_sold")])[0]
        revenue = demand * p

        if revenue > best_revenue:
            best_revenue = revenue
            best_price = p

    return best_price

df["optimal_price"] = df.apply(find_best_price, axis=1)

df[["price", "optimal_price"]].head()

revenues = []

for i in range(len(test)):
    row = test.iloc[i]
    price = find_best_price(row)
    revenue = price * row["units_sold"]
    revenues.append(revenue)

ml_revenue = sum(revenues)
print("ML Revenue:", ml_revenue)

baseline = test["dynamic_price"] * test["units_sold"]

lift = (ml_revenue - baseline.sum()) / baseline.sum() * 100

print("Baseline Revenue:", baseline.sum())
print("Lift (%):", lift)

explainer = shap.Explainer(model)
shap_values = explainer(X_test)

shap.plots.beeswarm(shap_values)

print("Insights:")
print("- Price negatively affects demand")
print("- Inventory increases demand")
print("- Competitor pricing impacts sales")