# -*- coding: utf-8 -*-
"""feature engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf1s-yl57bC9MnUZ74WL-kY9boq1_6o6

Data Loading
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/updated_retail_store_inventory (1).csv")

print("Dataset Shape:", df.shape)
df.head()

df.info()
df.dtypes

"""Feature Engineering"""

df = pd.read_csv("/content/clean_dynamic_pricing_dataset.csv")

df["profit_margin"] = df["price"] - df["cost"]

df["margin_percent"] = (df["price"] - df["cost"]) / df["price"]

df["demand_ratio"] = df["units_sold"] / (df["demand_forecast"] + 1)

df["inventory_pressure"] = df["units_sold"] / (df["inventory_level"] + 1)

df["competitor_gap"] = df["price"] - df["competitor_pricing"]

df["discounted_price"] = df["price"] * (1 - df["discount"])

df["revenue"] = df["units_sold"] * df["discounted_price"]

df["conversion_rate"] = df["units_sold"] / (df["no_of_visitors"] + 1)

df["price_demand_ratio"] = df["price"] / (df["units_sold"] + 1)

df["stock_remaining"] = df["inventory_level"] - df["units_sold"]

df["traffic_intensity"] = df["no_of_visitors"] / (df["inventory_level"] + 1)

df["date"] = pd.to_datetime(df["date"])

df["day_of_week"] = df["date"].dt.dayofweek
df["month"] = df["date"].dt.month
df["is_weekend"] = df["day_of_week"].isin([5,6]).astype(int)

df.to_csv("/content/feature_engineered_dataset.csv", index=False)

print("Feature engineered dataset saved successfully")

"""Saving Processed Dataset"""

import os
os.listdir("/content")

from google.colab import files
files.download("/content/clean_dynamic_pricing_dataset.csv")
files.download("/content/feature_engineered_dataset.csv")