# -*- coding: utf-8 -*-
"""AI price optima .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsRAZ575ndkkciPun_p5WadPhHqDKRh1
"""

import pandas as pd

# loading the cleaned dataset for feature engg.
df = pd.read_csv("/content/clean_dynamic_pricing_dataset.csv")
df.head()

# shows the amount of profit each product gains or checks how much profitable a product is.
df["profit_margin"] = df["price"] - df["cost"]

# checking the new column generated
df.head()

# normalizes the profit margin across different products of different price ranges
df["margin_percent"] = (df["profit_margin"]) / df["price"]

# demand ratio greater than 1 suggests higher than expected units sold
# and less than 1 means lower than expected demand
# +1 in demand forecast in denominator for avoiding division_by_zero error
df["demand_ratio"] = df["units_sold"] / (df["demand_forecast"] + 1)

# reflects how much available inventory is being sold.
# +1 in denominator for avoiding division_by_zero error
# inventory_pressure of 0.547 means that about 54.7% of the available inventory for product A was sold.
# This indicates a moderate level of inventory utilization.
# inventory_pressure is much lower, at 0.084. This suggests that only about 8.4% of the available inventory for product B was sold.
# A low inventory_pressure could indicate overstocking or low demand.
df["inventory_pressure"] = df["units_sold"] / (df["inventory_level"] + 1)

# compares price with competitor
df["competitor_gap"] = df["price"] - df["competitor_pricing"]

# checking columns generated
# shows last 5 rows of dataset
df.tail()

# gives price after discount for each product
df["discounted_price"] = df["price"] * (100 - df["discount"]) / 100

# total revenue gained for each product
df["revenue"] = df["units_sold"] * df["discounted_price"]

# measures how many visitors actually bought the product
# +1 in denominator for avoiding division_by_zero error
df["conversion_rate"] = df["units_sold"] / (df["visitors"] + 1)

# a higher price_demand_ratio could indicate that a product is priced relatively high compared to the number of units sold.
# a lower ratio might suggest that a product is priced lower, leading to higher sales
df["price_demand_ratio"] = df["price"] / (df["units_sold"] + 1)

# measures remaining stocks
df["stock_remaining"] = df["inventory_level"] - df["units_sold"]

# higher traffic_intensity suggest that the product is attracting a lot of visitors compared to the stock it holds, indicating high demand
# a lower value might indicate low traffic or overstocking.
df["traffic_intensity"] = df["visitors"] / (df["inventory_level"] + 1)

# creating time based features
# all columns here are numeric
df["date"] = pd.to_datetime(df["date"])
df["day_of_week"] =df["date"].dt.dayofweek
df["month"] = df["date"].dt.month
df["is_weekend"] =df["day_of_week"].isin([5,6]).astype(int)

# checking new columns
df.head()

# saving the dataset
df.to_csv("feature_engineered_dataset.csv", index=False)