# -*- coding: utf-8 -*-
"""datacleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf1s-yl57bC9MnUZ74WL-kY9boq1_6o6

Data Loading
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/updated_retail_store_inventory (1).csv")

print("Dataset Shape:", df.shape)
df.head()

df.info()
df.dtypes

"""Data Cleaning"""

df.columns = df.columns.str.lower().str.replace(" ", "_").str.replace("/", "_")

df.columns

df["date"] = pd.to_datetime(df["date"], format="mixed", errors="coerce")

df = df.dropna(subset=["date"])

df.isnull().sum()

df["price"].fillna(df["price"].median(), inplace=True)
df["cost"].fillna(df["cost"].median(), inplace=True)
df["inventory_level"].fillna(df["inventory_level"].median(), inplace=True)
df["demand_forecast"].fillna(df["demand_forecast"].median(), inplace=True)

df["weather_condition"].fillna(df["weather_condition"].mode()[0], inplace=True)
df["category"].fillna(df["category"].mode()[0], inplace=True)

print("Duplicate Rows:", df.duplicated().sum())
df.drop_duplicates(inplace=True)

"""Data Validation"""

df = df[df["inventory_level"] >= 0]

df = df[df["units_sold"] <= df["inventory_level"]]

df = df[df["price"] > 0]

df = df[df["cost"] <= df["price"]]

df["discount"] = df["discount"].clip(0,1)

df = df[df["no_of_visitors"] >= 0]

df["category"] = df["category"].str.strip().str.title()

df["weather_condition"] = df["weather_condition"].str.title()

"""Outlier Detection"""

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df["price"] >= lower) & (df["price"] <= upper)]