# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLDQYCP3SXJ-r72I3TWR0w2xus7I7n25
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import pickle
import pandas as pd
# Removed: from sklearn.linear_model import LinearRegression # Added for dummy model
# Removed: import numpy as np # Added for dummy model

app = FastAPI()

# --- Start of added code to create a dummy model.pkl ---
# This is a placeholder to resolve FileNotFoundError.
# If you have a specific model, please upload it to the Colab environment
# and remove this placeholder code.
# Removed: print("Creating a dummy model.pkl for demonstration purposes...")
# Removed: # Create a dummy model
# Removed: dummy_model = LinearRegression()
# Removed: # Fit it with some dummy data for it to be a valid model object
# Removed: # The input features list has 36 columns. Let's create dummy data with 36 features.
# Removed: num_features = 36 # Based on the 'columns' list in the predict function
# Removed: dummy_X = np.random.rand(10, num_features)
# Removed: dummy_y = np.random.rand(10)
# Removed: dummy_model.fit(dummy_X, dummy_y)

# Removed: with open("model.pkl", "wb") as f:
# Removed:    pickle.dump(dummy_model, f)
# Removed: print("dummy_model.pkl created.")
# --- End of added code ---

# Load your model
model = pickle.load(open("model.pkl", "rb"))
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/predict")
def predict(data: dict):

    import pandas as pd

    # All required columns
    columns = [
        'inventory_level', 'units_ordered', 'demand_forecast', 'price',
        'discount', 'holiday/promotion', 'competitor_pricing', 'visitors',
        'cost', 'profit_margin', 'margin_percent', 'demand_ratio',
        'inventory_pressure', 'competitor_gap', 'discounted_price', 'revenue',
        'conversion_rate', 'price_demand_ratio', 'stock_remaining',
        'traffic_intensity', 'day_of_week', 'month', 'is_weekend',
        'category_Electronics', 'category_Furniture', 'category_Groceries',
        'category_Toys', 'region_North', 'region_South', 'region_West',
        'weather_condition_Rainy', 'weather_condition_Snowy',
        'weather_condition_Sunny', 'seasonality_Spring', 'seasonality_Summer',
        'seasonality_Winter'
    ]

    # Create row with default 0
    input_data = {col: 0 for col in columns}

    # Update with user input
    input_data.update(data)

    df = pd.DataFrame([input_data])

    result = model.predict(df)

    return {"prediction": float(result[0])}

@app.post("/graph")
def graph(data: dict):
    import pandas as pd

    columns = [
        'inventory_level', 'units_ordered', 'demand_forecast', 'price',
        'discount', 'holiday/promotion', 'competitor_pricing', 'visitors',
        'cost', 'profit_margin', 'margin_percent', 'demand_ratio',
        'inventory_pressure', 'competitor_gap', 'discounted_price', 'revenue',
        'conversion_rate', 'price_demand_ratio', 'stock_remaining',
        'traffic_intensity', 'day_of_week', 'month', 'is_weekend',
        'category_Electronics', 'category_Furniture', 'category_Groceries',
        'category_Toys', 'region_North', 'region_South', 'region_West',
        'weather_condition_Rainy', 'weather_condition_Snowy',
        'weather_condition_Sunny', 'seasonality_Spring', 'seasonality_Summer',
        'seasonality_Winter'
    ]

    prices = list(range(50, 200, 10))
    predictions = []

    for p in prices:

        # Step 1: Create full input with all columns
        input_data = {col: 0 for col in columns}
        input_data.update(data)

        # Step 2: Update price + dependent features (VERY IMPORTANT)
        input_data["price"] = p
        input_data["discounted_price"] = p - (p * input_data.get("discount", 0) / 100)
        input_data["price_demand_ratio"] = p / (input_data.get("demand_forecast", 1))

        # Step 3: Convert to DataFrame
        df = pd.DataFrame([input_data])

        # Step 4: Predict
        pred = model.predict(df)[0]

        predictions.append(float(pred))

    return {
        "prices": prices,
        "predictions": predictions
    }