# -*- coding: utf-8 -*-
"""FeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TmPu7XuQZxeHZUU_NxzPCw6yvMpJLwq3
"""

import pandas as pd
df = pd.read_csv("clean_dynamic_pricing_dataset.csv")

# Step 2: Profit Margin — how much money made per unit
df["profit_margin"] = df["price"] - df["cost"]

# Step 3: Margin % — profit as a fraction of price (normalized)
df["margin_percent"] = (df["price"] - df["cost"]) / df["price"]

# Step 4: Demand Ratio — did we sell more or less than predicted?

df["demand_ratio"] = df["units_sold"] / (df["demand_forecast"] + 1)

# Step 5: Inventory Pressure — how fast is stock depleting?
df["inventory_pressure"] = df["units_sold"] / (df["inventory_level"] + 1)

# Step 6: Competitor Gap — are we cheaper or more expensive than rivals?
df["competitor_gap"] = df["price"] - df["competitor_pricing"]

# Step 7: Discounted Price — what customer actually pays
df["discounted_price"] = df["price"] * (1 - df["discount"])

# Step 8: Revenue — total money earned
df["revenue"] = df["units_sold"] * df["discounted_price"]

# Step 9: Conversion Rate — % of visitors who bought
df["conversion_rate"] = df["units_sold"] / (df["visitors"] + 1)

# Step 10: Price Demand Ratio — price sensitivity indicator
df["price_demand_ratio"] = df["price"] / (df["units_sold"] + 1)

# Step 11: Stock Remaining — units left after sales (stockout risk)
df["stock_remaining"] = df["inventory_level"] - df["units_sold"]

# Step 12: Traffic Intensity — how busy is the store relative to stock?
df["traffic_intensity"] = df["visitors"] / (df["inventory_level"] + 1)

df["date"] = pd.to_datetime(df["date"])

df["day_of_week"] = df["date"].dt.dayofweek
# Monday=0, Tuesday=1, ..., Sunday=6

df["month"] = df["date"].dt.month
# January=1, February=2, ..., December=12

df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)

df.to_csv("feature_engineered_dataset.csv", index=False)
print("Feature engineering complete! Shape:", df.shape)
print("New columns:", df.columns.tolist())

