# -*- coding: utf-8 -*-
"""AI price optima cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sixjhoWakEEYWuNqvmUKmOK5Xc4TApqx
"""

import pandas as pd

# loading the dataset

df = pd.read_csv("/content/Updated_dynamic-pricing-dataset.csv")
df.head()

# provides all the major information about dataset like number of rows and columns, non null count, columns data type (does not need to check everything separately)
df.info()

# converts date column type to datetime data type
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

# checks the datatypes of each column
df.dtypes

# uniqyue values for each categorical column
for col in df.select_dtypes(include='object').columns:
    print(df[col].unique())

# gives count of null values in each column
df.isnull().sum()

"""Incase there is any missing values, we can fill that... like for numeric, we can use median to fill and for categorical we can use mode.

 example:-

 df["Price"].fillna(df["Price"].median(), inplace=True)

 df["Weather Condition"].fillna(df["Weather Condition"].mode()[0], inplace=True)

 But in our dataset, we do not have any null values.
"""

# represents if current row is duplicate of the previous row
df.duplicated()

# gives count of duplicate rows in dataset
df.duplicated().sum()

# drops duplicate rows if any
df.drop_duplicates(inplace=True)

# in our dataset we do not have any duplicate row so it's optional

# shows all the columns in dataset
df.columns

# Standardizing column names for consistency and ease of access during data manipulation and analysis.
# This ensures all column names are lowercase and spaces are replaced with underscores, creating a uniform format.
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

#  gives rows whose inventory level  is negative
df[df["inventory_level"] < 0]

# here it only takes those rows with inventory level greater or equal to 0 and stores in df
# but in our case, we do not have any rows with negative inventory level, so its optional
df = df[df["inventory_level"] >= 0]

# checks for rows where units sold is greater than inventory level
df[df["units_sold"] > df["inventory_level"]]

# checks for rows where  price is less than cost
df[df["cost"] > df["price"]]

# checks for rows where discount is less than 0 or greater than 100
df[(df["discount"] < 0) | (df["discount"] > 100)]

# checks minimum and maximum value of discount
print(f"Minimum discount value: {df['discount'].min()}")
print(f"Maximum discount value: {df['discount'].max()}")

# sets discount value to 0 where discount is less than 0 and sets to 100 where discount more than 100
# since in dataset we only have discount values ranging 0 to 20, so we can skip this
df["discount"] =df["discount"].clip(0,100)
df.head()

# checks if no. of visitors are negative
df[df["visitors"] < 0]

# drops all negative visitors
# dataset do not have any negative number of visitors so it too can be skipped
df = df[df["visitors"] >= 0]

# Cleans categorical column values to avoid duplication (e.g., 'north' vs. 'North'),
# excluding 'store_id' and 'product_id' from standardization.
excluded_cols = ['store_id', 'product_id']
for col in df.select_dtypes(include='object').columns:
    if col not in excluded_cols:
        df[col] = df[col].str.strip().str.title()
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Get numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Create a boxplot for each numerical column to check for outliers
for col in numerical_cols:
    plt.figure(figsize=(10, 6))
    sns.boxplot(y=df[col])
    plt.title(f'Boxplot of {col}')
    plt.ylabel(col)
    plt.show()

# detects and removes the outliers using inter quartile range method
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR
df = df[(df["price"] >= lower) & (df["price"] <= upper)]

# saved the cleaned csv file
df.to_csv('clean_dynamic_pricing_dataset.csv', index=False)